export const formatWalletAddress = (address: string | undefined): string => {
  if (!address || typeof address !== 'string' || address.length < 10) {
    return 'invalid address'
  }
  return `0x${address.slice(2, 6)}...${address.slice(-4)}`
}

// basically testing a string to see if it is in format generated by formatWalletAddress
export const isDefaultDisplayNameFormat = (displayName: string | undefined): boolean => {
  return displayName ? /^0x.{4}\.\.\..{4}$/.test(displayName) : false
}
